### ISSUE TITLE
[2.4.10] CUPS web interface administration via checkboxes not working setting everything back to default

### ISSUE THREAD

**Issue by r3n3647** [OpenPrinting/cups#1059]
**Describe the bug**
If you make any changes to the settings in the administration tab of the cups web interface using the checkboxes all settings made are ignored but reset to back default and any manually made changes to /etc/cups/cupsd.conf are lost.

If there were no previous changes to /etc/cups/cupsd.conf and you try to make some using the checkboxes cups will report 'server not restarted because there were no changes'.

Configuration is only possible if you edit /etc/cups/cupsd.conf manually in console or via 'edit configuration file' button in web interface but not using the checkboxes. Using the checkboxes will always lead to reset of all settings to defaults.

**To Reproduce**
1. Go to server:631 in any browser -> open administration tab -> enter authorization
2. Click on any checkbox in the 'server-settings' area
3. Click on 'change settings'
4. Every setting will be reset to default - no matter what you've set

**Expected behavior**
After making any changes to server settings using the checkboxes these should be applied to /etc/cups/cupsd.conf instead of just replacing it with /etc/cupsd.conf.default

**System Information:**
 - ArchLinux 6.10.10-arch1-1  x86_64 GNU/Linux
 - any browser
 - CUPS version 2.4.10

**Comment by zdohnal** [comment]
Fixed by https://github.com/OpenPrinting/cups/commit/09bfbb6df5 .

**Comment by r3n3647** [comment]
Completed? Fixed?
Using Archlinux latest bleedeing edge CUPS 2.4.10 and the issue is still present!
This is frustrating!

**Comment by zdohnal** [comment]
The issue is fixed in the current master branch, contact your distro maintainer to backport the fix in the meantime.
